# Generated by Django 4.2.4 on 2023-08-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="auctionListing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("startingBid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("imgUrl", models.TextField()),
                ("catagory", models.CharField(max_length=64)),
            ],
        ),
    ]
