# Generated by Django 4.2.4 on 2023-08-23 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auctionlisting"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="fromUser",
            field=models.ManyToManyField(
                blank=True, related_name="postedListings", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="topBid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="watchItem",
            field=models.ManyToManyField(
                blank=True, related_name="watchingUsers", to="auctions.auctionlisting"
            ),
        ),
        migrations.CreateModel(
            name="comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "fromUser",
                    models.ManyToManyField(
                        blank=True, related_name="comments", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "listing",
                    models.ManyToManyField(
                        blank=True,
                        related_name="comments",
                        to="auctions.auctionlisting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="bid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bidAmount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fromUser",
                    models.ManyToManyField(
                        blank=True, related_name="bids", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "listing",
                    models.ManyToManyField(
                        blank=True, related_name="bids", to="auctions.auctionlisting"
                    ),
                ),
            ],
        ),
    ]
