# Generated by Django 4.2.4 on 2023-08-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auctionlisting_fromuser_auctionlisting_topbid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="categoryModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name="auctionlisting",
            name="catagory",
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="postedListings", to="auctions.categorymodel"
            ),
        ),
    ]
