# Generated by Django 4.2.4 on 2023-08-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_categorymodel_remove_auctionlisting_catagory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
    ]
